version: '3'
services:
  db:
    image: postgres:16.0
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=DEMODB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  awwesome:
    image: node:alpine
    container_name: awwesome
    ports:
      - "8000:8000"
    working_dir: /src/app
    volumes:
        - ./:/src/app
    tty: true
    command: npm run dev

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8080:8080"
